services:
    phpbb.sessionsauthbundle.tblprefix_subscriber:
        class: phpBB\SessionsAuthBundle\Subscriber\TablePrefixSubscriber
        public: false
        arguments: ["%phpbb_sessions_auth.database.prefix%"]
        tags:
            - { name: doctrine.event_subscriber }

    phpbb.sessionsauthbundle.phpbb_authenticator:
        class:  phpBB\SessionsAuthBundle\Security\PhpbbSessionAuthenticator
        public: false
        arguments:
            - "%phpbb_sessions_auth.session.cookie_name%"
            - "%phpbb_sessions_auth.session.login_page%"
            - "%phpbb_sessions_auth.session.force_login%"

    phpbb.sessionsauthbundle.phpbb_user_provider:
        class:  phpBB\SessionsAuthBundle\Security\PhpbbUserProvider
        public: false
        arguments: ["@doctrine", "%phpbb_sessions_auth.database.entity_manager%"]
        calls: [[setRoles, ["%phpbb_sessions_auth.roles%"]], [setIpCheckLength, ["%phpbb_sessions_auth.session.ip_check%"]]]
