parameters:

services:
    phpbb.sessionsauthbundle.tblprefix_subscriber:
        class: phpBB\SessionsAuthBundle\Subscriber\TablePrefixSubscriber
        arguments: [%phpbb_sessions_auth.database.prefix%]
        tags:
            - { name: doctrine.event_subscriber }

    phpbb.sessionsauthbundle.phpbb_authenticator:
        class:  phpBB\SessionsAuthBundle\Authentication\phpBBSessionAuthenticator
        public: false
        arguments:
            - %phpbb_sessions_auth.database.cookiename%
            - @request_stack